name: Auto release excalidraw preview
on:
  issue_comment:
    types: [created, edited]

jobs:
  Auto-release-excalidraw-preview:
    name: Auto release preview
    if: github.event.comment.body == '@excalibot trigger release' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: React to release comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          token: ${{ secrets.PUSH_TRANSLATIONS_COVERAGE_PAT }}
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b # v9.0.0
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ steps.sha.outputs.result }}
          fetch-depth: 2
      - name: Setup Node.js 22.x
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
      - name: Install Yarn 1.22.22
        run: npm install --global yarn@1.22.22 --no-fund --no-audit
      - name: Set up publish access
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Auto release preview
        id: "autorelease"
        run: |
          node scripts/yarn-install-quiet.mjs add @actions/core -W --silent
          yarn autorelease preview ${{ github.event.issue.number }}
      - name: Post comment post release
        if: always()
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          token: ${{ secrets.PUSH_TRANSLATIONS_COVERAGE_PAT }}
          issue-number: ${{ github.event.issue.number }}
          body: "@${{ github.event.comment.user.login }} ${{ steps.autorelease.outputs.result }}"
